"""Turning IATI codes into words a person can read.

Published data is full of codes. An activity comes back reporting `11220` and `PS`,
which are precise and unreadable, and an agent asked to summarise it has nothing to
work with.

The lists are bundled rather than fetched, so this needs no network, no key, and none
of the Datastore's 100 calls a week. They are regenerated by
`scripts/refresh_codelists.py`, which records where the data came from and when.

One rule matters more than the rest: **a code is only meaningful inside its
vocabulary.** IATI lets a publisher report sectors against their own numbering, and
resolving one of those against the OECD DAC list would attach a real, wrong name to it.
Naming something incorrectly is worse than leaving it as a number, so an unrecognised
vocabulary is left alone.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

BUNDLE = Path(__file__).parent / "codelists.json"

#: IATI SectorVocabulary codes whose sector numbering is the OECD DAC one, which is
#: what the bundled Sector list contains. Anything else is a publisher's own scheme.
DAC_SECTOR_VOCABULARIES = frozenset({"", "1", "2"})


@dataclass(frozen=True, slots=True)
class Codelists:
    """Code to name, for the lists that appear in output people read."""

    lists: dict[str, dict[str, str]]
    source: str = ""
    fetched: str = ""

    def name(self, listname: str, code: str) -> str | None:
        """The readable name, or None when the code is not in that list."""
        if not code:
            return None
        return self.lists.get(listname, {}).get(str(code).strip())

    def label(self, listname: str, code: str) -> str:
        """`Name (code)` where the code resolves, otherwise the bare code.

        Keeps the code alongside the name rather than replacing it. The code is what
        anyone cross-referencing the published data will search for.
        """
        found = self.name(listname, code)
        return f"{found} ({code})" if found else str(code)

    def labels(self, listname: str, codes: tuple[str, ...]) -> tuple[str, ...]:
        return tuple(self.label(listname, code) for code in codes)

    def sector_labels(
        self, codes: tuple[str, ...], vocabularies: tuple[str, ...] = ()
    ) -> tuple[str, ...]:
        """Resolve sector codes, but only where the vocabulary is the DAC one.

        With no vocabulary published, the DAC list is assumed, which is what the
        standard's own default says. Where a publisher names a different vocabulary,
        the code is returned untouched rather than given someone else's name.
        """
        if vocabularies and len(vocabularies) == len(codes):
            return tuple(
                self.label("Sector", code)
                if str(vocab).strip() in DAC_SECTOR_VOCABULARIES
                else str(code)
                for code, vocab in zip(codes, vocabularies, strict=True)
            )
        if vocabularies and not set(map(str, vocabularies)) <= DAC_SECTOR_VOCABULARIES:
            # Mixed or unaligned vocabularies, at least one of them not DAC. There is
            # no safe way to tell which code belongs to which, so none are resolved.
            return codes
        return self.labels("Sector", codes)

    def __len__(self) -> int:
        return sum(len(entries) for entries in self.lists.values())


@lru_cache(maxsize=1)
def bundled() -> Codelists:
    """The codelists shipped with the package. Read once, reused."""
    if not BUNDLE.exists():  # pragma: no cover - only if packaging went wrong
        return Codelists(lists={})
    data = json.loads(BUNDLE.read_text(encoding="utf-8"))
    return Codelists(
        lists=data.get("lists", {}),
        source=data.get("source", ""),
        fetched=data.get("fetched", ""),
    )


__all__ = ["BUNDLE", "DAC_SECTOR_VOCABULARIES", "Codelists", "bundled"]
